version: "3.9"

services:
  app:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8001:8080"
    network_mode: bridge
    extra_hosts:
      - "mongoservice:172.17.0.1"
